{
    'name': 'Rami\'s Bike Workshop',
    'version': '19.0.2.0.0',
    'summary': 'Manage bikes, rentals, repairs, and spare parts',
    'category': 'Sales/Rental',
    'author': 'Shahed Alawneh',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'contacts',
        'product',
        'stock',
    ],
    'data': [
        'security/bike_security.xml',
        'security/ir.model.access.csv',
        'data/bike_sequence.xml',
        'views/bike_views.xml',
        'views/bike_rental_views.xml',
        'views/bike_repair_views.xml',
        'views/res_partner_views.xml',
        'views/product_views.xml',
        'data/res_partner_category_data.xml',
        'reports/rental_agreement_report.xml',
        'views/res_users_views.xml',
            ],
    'installable': True,
    'application': True,
    'auto_install': False,
}